//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class article
    {
        public int id_article { get; set; }
        public string titre { get; set; }
        public string en_tete { get; set; }
        public string corpsarticle { get; set; }
        public string introduction { get; set; }
        public string conclusion { get; set; }
        public int id_langue { get; set; }
        public int id_personnes { get; set; }
        public System.DateTime DateCreation { get; set; }
        public System.DateTime DateModification { get; set; }
    }
}
