//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class companie
    {
        public int id_compagnie { get; set; }
        public string guid { get; set; }
        public string nom { get; set; }
        public int id_contact { get; set; }
        public string guid_contact { get; set; }
        public string website { get; set; }
        public int id_user1 { get; set; }
        public int id_user2 { get; set; }
        public int id_user3 { get; set; }
        public string logo { get; set; }
        public Nullable<int> idsport { get; set; }
        public System.DateTime DateCreation { get; set; }
        public System.DateTime DateModification { get; set; }
    }
}
