//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class contact
    {
        public int id_contact { get; set; }
        public Nullable<int> nocivique { get; set; }
        public string nomrue { get; set; }
        public string codepostal { get; set; }
        public string ville { get; set; }
        public string email { get; set; }
        public string cellphone { get; set; }
        public string homephone { get; set; }
        public string id_country { get; set; }
        public System.DateTime DateCreation { get; set; }
        public System.DateTime DateModification { get; set; }
    }
}
