//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class country
    {
        public int id { get; set; }
        public string iso { get; set; }
        public string nom { get; set; }
        public string nicenom { get; set; }
        public string iso3 { get; set; }
        public Nullable<short> numcode { get; set; }
        public Nullable<int> phonecode { get; set; }
    }
}
