//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class dateheuredebut
    {
        public int id { get; set; }
        public string guid { get; set; }
        public Nullable<System.DateTime> datedebut { get; set; }
        public byte[] heuredebut { get; set; }
        public Nullable<int> objetid { get; set; }
        public string objetguid { get; set; }
        public System.DateTime DateDebutTimeStamp { get; set; }
    }
}
