//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class evenement
    {
        public int id_evenement { get; set; }
        public string titre { get; set; }
        public int iduser { get; set; }
        public Nullable<int> id_article { get; set; }
        public string description { get; set; }
        public string introduction { get; set; }
        public string conclusion { get; set; }
        public string website { get; set; }
        public Nullable<System.DateTime> datedebut { get; set; }
        public Nullable<System.DateTime> datefin { get; set; }
        public Nullable<int> id_sport { get; set; }
        public System.DateTime DateCreation { get; set; }
        public System.DateTime DateModification { get; set; }
    }
}
