//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class joueurs
    {
        public int id { get; set; }
        public Nullable<int> idpersonne { get; set; }
        public Nullable<int> id_niveau { get; set; }
        public Nullable<int> ratingsatisfaction { get; set; }
        public Nullable<int> idsport { get; set; }
        public Nullable<int> idcalendrierdisponibilite { get; set; }
        public Nullable<int> idtyperencontre { get; set; }
        public System.DateTime DateCreation { get; set; }
        public System.DateTime Datemodification { get; set; }
    }
}
