//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class listejoueurequipe
    {
        public int id_team { get; set; }
        public Nullable<int> joueur1 { get; set; }
        public Nullable<int> joueur2 { get; set; }
        public Nullable<int> joueur3 { get; set; }
        public Nullable<int> joueur4 { get; set; }
        public Nullable<int> joueur5 { get; set; }
        public Nullable<int> joueur6 { get; set; }
        public Nullable<int> joueur7 { get; set; }
        public Nullable<int> joueur8 { get; set; }
        public Nullable<int> joueur9 { get; set; }
        public Nullable<int> joueur10 { get; set; }
        public Nullable<int> joueur11 { get; set; }
        public Nullable<int> joueur12 { get; set; }
        public Nullable<int> joueur13 { get; set; }
        public Nullable<int> joueur14 { get; set; }
        public Nullable<int> joueur15 { get; set; }
        public Nullable<int> joueur16 { get; set; }
        public Nullable<int> joueur17 { get; set; }
        public Nullable<int> joueur18 { get; set; }
        public Nullable<int> joueur19 { get; set; }
        public Nullable<int> joueur20 { get; set; }
        public Nullable<int> joueur21 { get; set; }
        public Nullable<int> joueur22 { get; set; }
        public Nullable<int> joueur23 { get; set; }
        public Nullable<int> joueur24 { get; set; }
        public Nullable<int> joueur25 { get; set; }
        public Nullable<int> joueur26 { get; set; }
        public Nullable<int> joueur27 { get; set; }
        public Nullable<int> joueur28 { get; set; }
        public Nullable<int> joueur29 { get; set; }
        public Nullable<int> joueur30 { get; set; }
        public Nullable<int> joueur31 { get; set; }
        public Nullable<int> guidteam { get; set; }
        public System.DateTime DateCreation { get; set; }
        public System.DateTime DateModification { get; set; }
    }
}
