//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Spark_devEntities : DbContext
    {
        public Spark_devEntities()
            : base("name=Spark_devEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<article> article { get; set; }
        public virtual DbSet<calendrierdisponibilite> calendrierdisponibilite { get; set; }
        public virtual DbSet<classificationsport> classificationsport { get; set; }
        public virtual DbSet<clubs> clubs { get; set; }
        public virtual DbSet<commande> commande { get; set; }
        public virtual DbSet<companie> companie { get; set; }
        public virtual DbSet<contact> contact { get; set; }
        public virtual DbSet<conversation> conversation { get; set; }
        public virtual DbSet<country> country { get; set; }
        public virtual DbSet<dateheuredebut> dateheuredebut { get; set; }
        public virtual DbSet<dateheurefin> dateheurefin { get; set; }
        public virtual DbSet<equipe> equipe { get; set; }
        public virtual DbSet<evenement> evenement { get; set; }
        public virtual DbSet<joueurs> joueurs { get; set; }
        public virtual DbSet<listejoueurequipe> listejoueurequipe { get; set; }
        public virtual DbSet<maintypesport> maintypesport { get; set; }
        public virtual DbSet<messages> messages { get; set; }
        public virtual DbSet<migrations> migrations { get; set; }
        public virtual DbSet<niveau> niveau { get; set; }
        public virtual DbSet<pays> pays { get; set; }
        public virtual DbSet<personnes> personnes { get; set; }
        public virtual DbSet<product> product { get; set; }
        public virtual DbSet<sports> sports { get; set; }
        public virtual DbSet<subclassessports> subclassessports { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tb_sports> tb_sports { get; set; }
        public virtual DbSet<typerencontre> typerencontre { get; set; }
        public virtual DbSet<userslog> userslog { get; set; }
        public virtual DbSet<Amities> Amities { get; set; }
    }
}
