//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class typerencontre
    {
        public int id { get; set; }
        public int idPersonne { get; set; }
        public int idSport { get; set; }
        public Nullable<short> reprise { get; set; }
        public Nullable<short> competition { get; set; }
        public Nullable<short> entrainement { get; set; }
        public Nullable<short> amical { get; set; }
    }
}
